version: '3'

services:
  app:
    image: 'node:16-alpine'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - '.:/home/server'
    working_dir: /home/server
    command: npm run dev
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379