version: '3'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229 # debugger
    environment:
      - NODE_ENV=development
    volumes:
      - '.:/home/server'
    working_dir: /home/server
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ../redis-insight/:/data